version: '3.8'
services:
  db:
    env_file: .env
    image: postgres:14.6
    container_name: askme
    volumes:
      - db-askme:/var/lib/postgresql/data
  app:
    image: fasolshik/askme
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
    environment:
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
volumes:
  db-askme: